version: "3.8"
services:
  gql:
    container_name: gql
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - DB_HOST=test
      - DB_USER=test
      - DB_NAME=test
      - DB_PASSWORD=root
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - mysql_db
  mysql_db:
    container_name: mysql_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test