package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"github.com/gari8/gqlgen-pct/domain"
	"github.com/gari8/gqlgen-pct/loader"
)

// Programs is the resolver for the programs field.
func (r *placeResolver) Programs(ctx context.Context, obj *domain.Place, programType *domain.ProgramType) ([]*domain.Program, error) {
	return loader.LoadPrograms(ctx, obj.ID, programType)
}

// Places is the resolver for the places field.
func (r *queryResolver) Places(ctx context.Context, placeType *domain.PlaceType) ([]*domain.Place, error) {
	return r.Resolver.PlaceRepo.FindAll(placeType)
}

// Place returns PlaceResolver implementation.
func (r *Resolver) Place() PlaceResolver { return &placeResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver {
	return &queryResolver{r}
}

type placeResolver struct{ *Resolver }
type queryResolver struct {
	*Resolver
}
