package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"github.com/gari8/gqlgen-pct/domain"
	"github.com/gari8/gqlgen-pct/loader"
)

// Place is the resolver for the place field.
func (r *programResolver) Place(ctx context.Context, obj *domain.Program) (*domain.Place, error) {
	return loader.LoadPlace(ctx, obj.PlaceID)
}

// Programs is the resolver for the programs field.
func (r *queryResolver) Programs(ctx context.Context, programType *domain.ProgramType) ([]*domain.Program, error) {
	return r.ProgramRepo.FindAll(programType, nil)
}

// Program is the resolver for the program field.
func (r *queryResolver) Program(ctx context.Context, id string) (*domain.Program, error) {
	return r.ProgramRepo.FindByID(id)
}

// Program returns ProgramResolver implementation.
func (r *Resolver) Program() ProgramResolver { return &programResolver{r} }

type programResolver struct{ *Resolver }
