version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.1

executors:
  default:
    docker:
      - image: cimg/base:2023.01

jobs:
  lint_and_test:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: |
            go mod download
            go install honnef.co/go/tools/cmd/staticcheck@latest
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run lint
          command: staticcheck ./...
      - run:
          name: Prepare for docker build
          command: |
            mkdir -p /tmp/output
            cp -r . /tmp/output
      - persist_to_workspace:
          root: /tmp/output
          paths:
            - .

workflows:
  sample:
    jobs:
      - lint_and_test
      - gcp-gcr/build_and_push:
          name: build-and-push-app
          executor: default
          attach_workspace: true
          setup_remote_docker: true
          remote_docker_version: default
          workspace_root: /tmp/output
          docker_context: .
          dockerfile: Dockerfile
          path: .
          registry_url: $GAR_REGISTRY_URL
          gcloud_service_key: $GCLOUD_SERVICE_KEY
          gcloud_project_id: $GCLOUD_PROJECT_ID
          google_compute_region: $GOOGLE_COMPUTE_REGION
          google_compute_zone: $GOOGLE_COMPUTE_ZONE
          image: $GAR_IMAGE_REPO/app
          tag: $CIRCLE_SHA1
          requires:
            - lint-and-test
          filters:
            branches:
              only: main